name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0<3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_core_platform_interface: ^5.0.0
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.5.1

#  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
