// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bnYfs5qivlNaFlOYxwMSusZhBddBjlc',
    appId: '1:516075543756:web:37e3e65700556ea878b669',
    messagingSenderId: '516075543756',
    projectId: 'flash-chat-2409f',
    authDomain: 'flash-chat-2409f.firebaseapp.com',
    storageBucket: 'flash-chat-2409f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEg0JU_yq28X8hQwdYge0jrshn0tNSRVM',
    appId: '1:516075543756:android:1a665a1d5f1a5dcd78b669',
    messagingSenderId: '516075543756',
    projectId: 'flash-chat-2409f',
    storageBucket: 'flash-chat-2409f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4_OCJ2J86v5tqfLW_qeM1Rf2iBvSThFs',
    appId: '1:516075543756:ios:0d59519ef9d4913078b669',
    messagingSenderId: '516075543756',
    projectId: 'flash-chat-2409f',
    storageBucket: 'flash-chat-2409f.appspot.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
